#!/bin/sh
set -e

# Get the directory where this script is located
bin_dir="$(cd "$(dirname "$0")" && pwd)"

{ echo "Checking licenses ..."; } 2>/dev/null
"${bin_dir}/list-licenses" | "${bin_dir}/license-engine.sh"
